GET http://localhost:9000/date

###
GET http://localhost:9000/students
Accept: application/json

###
GET http://localhost:9000/students/20
Accept: application/json

###
POST http://localhost:9000/students
Content-Type: application/json

{
    "name": "Pedro Pereira",
    "number": 5
}

